In [19]:
import numpy as np
import random

Seed and Input Vector Bitstream Parameters

In [20]:
## System defination 
input_len = 512
output_len = 256
random.seed(45)

Seed and Input Vector Bitstream

In [21]:
input = [random.randint(0,1) for _ in range(input_len)] 
print(input)

[1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 

In [22]:
seed = [random.randint(0,1) for _ in range(input_len + output_len - 1)]
print(seed)

[1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 

Matrix Multiplication

In [23]:
## Toeplitz constuction
def toep_construction(seed, row, clm):
    toep = np.zeros((row, clm))
    for i in range(0,row):
        for j in range(0,clm):
            toep[i,j] = seed[row - 1 + j - i]
    return toep

In [24]:
# for hashing input = coloumns and output = rows
# generate toep
toep = toep_construction(seed[::-1], output_len, input_len)
print(toep)

[[0. 0. 1. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [1. 1. 0. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]]


In [25]:
# Matrix mul
output_matrix_mul = np.dot(toep, input) 
print(output_matrix_mul)

[120. 123. 109. 119. 118. 118. 115. 118. 124. 121. 116. 123. 124. 133.
 120. 127. 123. 125. 123. 128. 126. 117. 120. 124. 120. 119. 121. 121.
 118. 115. 117. 108. 115. 114. 114. 121. 119. 120. 131. 116. 119. 115.
 122. 116. 124. 122. 120. 107. 118. 123. 120. 115. 111. 111. 123. 124.
 117. 128. 123. 102. 124. 119. 115. 129. 105. 117. 121. 123. 107. 119.
 121. 118. 120. 131. 109. 123. 123. 115. 122. 131. 112. 124. 128. 117.
 126. 126. 121. 121. 124. 120. 138. 113. 124. 123. 115. 124. 123. 123.
 120. 120. 121. 128. 112. 117. 126. 117. 119. 122. 120. 118. 126. 122.
 126. 123. 120. 120. 124. 123. 118. 131. 115. 128. 121. 122. 128. 125.
 134. 125. 121. 124. 115. 119. 129. 126. 124. 119. 114. 119. 124. 120.
 119. 128. 128. 124. 125. 128. 112. 128. 129. 125. 123. 123. 129. 129.
 132. 118. 134. 135. 118. 130. 140. 125. 131. 125. 125. 123. 131. 109.
 127. 109. 119. 120. 127. 127. 112. 117. 127. 118. 124. 124. 115. 135.
 133. 130. 127. 133. 124. 133. 129. 140. 129. 133. 120. 125. 122. 121.
 112. 

Convolution method

In [26]:
output_linear_conv = np.convolve(seed, input, mode='valid') 
print(output_linear_conv)

[120 123 109 119 118 118 115 118 124 121 116 123 124 133 120 127 123 125
 123 128 126 117 120 124 120 119 121 121 118 115 117 108 115 114 114 121
 119 120 131 116 119 115 122 116 124 122 120 107 118 123 120 115 111 111
 123 124 117 128 123 102 124 119 115 129 105 117 121 123 107 119 121 118
 120 131 109 123 123 115 122 131 112 124 128 117 126 126 121 121 124 120
 138 113 124 123 115 124 123 123 120 120 121 128 112 117 126 117 119 122
 120 118 126 122 126 123 120 120 124 123 118 131 115 128 121 122 128 125
 134 125 121 124 115 119 129 126 124 119 114 119 124 120 119 128 128 124
 125 128 112 128 129 125 123 123 129 129 132 118 134 135 118 130 140 125
 131 125 125 123 131 109 127 109 119 120 127 127 112 117 127 118 124 124
 115 135 133 130 127 133 124 133 129 140 129 133 120 125 122 121 112 128
 120 126 119 126 123 128 118 124 120 120 118 124 124 122 122 122 123 125
 127 121 125 120 120 133 127 121 113 120 128 119 126 121 122 133 122 131
 136 117 123 132 132 117 119 134 120 119 125 119 12

FFT Method

In [27]:
zero_pad = len(seed) - len(input)
temp_input = np.pad(input, (0, zero_pad))

In [28]:
output_FFT_based_conv = np.fft.ifft(np.fft.fft(temp_input)*np.fft.fft(seed))
print(abs(output_FFT_based_conv[-output_len:]))

[120. 123. 109. 119. 118. 118. 115. 118. 124. 121. 116. 123. 124. 133.
 120. 127. 123. 125. 123. 128. 126. 117. 120. 124. 120. 119. 121. 121.
 118. 115. 117. 108. 115. 114. 114. 121. 119. 120. 131. 116. 119. 115.
 122. 116. 124. 122. 120. 107. 118. 123. 120. 115. 111. 111. 123. 124.
 117. 128. 123. 102. 124. 119. 115. 129. 105. 117. 121. 123. 107. 119.
 121. 118. 120. 131. 109. 123. 123. 115. 122. 131. 112. 124. 128. 117.
 126. 126. 121. 121. 124. 120. 138. 113. 124. 123. 115. 124. 123. 123.
 120. 120. 121. 128. 112. 117. 126. 117. 119. 122. 120. 118. 126. 122.
 126. 123. 120. 120. 124. 123. 118. 131. 115. 128. 121. 122. 128. 125.
 134. 125. 121. 124. 115. 119. 129. 126. 124. 119. 114. 119. 124. 120.
 119. 128. 128. 124. 125. 128. 112. 128. 129. 125. 123. 123. 129. 129.
 132. 118. 134. 135. 118. 130. 140. 125. 131. 125. 125. 123. 131. 109.
 127. 109. 119. 120. 127. 127. 112. 117. 127. 118. 124. 124. 115. 135.
 133. 130. 127. 133. 124. 133. 129. 140. 129. 133. 120. 125. 122. 121.
 112. 

NTT

In [29]:
def NTT(x, phi, mod):
    N = len(x)
    if N == 1:
        return x

    E = NTT(x[0::2], pow(phi, 2, mod), mod)
    O = NTT(x[1::2], pow(phi, 2, mod), mod)

    X = [0] * N
    w = 1

    for k in range(N // 2):
        t = (w * O[k]) % mod
        X[k] = (E[k] + t) % mod
        X[k + N//2] = (E[k] - t) % mod
        w = (w * phi) % mod

    return X


In [30]:
def inverse_NTT(a, root, mod):
    n = len(a)

    # Inverse root
    inv_root = pow(root, mod - 2, mod)

    # Apply forward NTT using inverse root
    res = NTT(a, inv_root, mod)

    # Multiply by n^{-1}
    inv_n = pow(n, mod - 2, mod)
    for i in range(n):
        res[i] = (res[i] * inv_n) % mod

    return res


In [31]:
temp_input_ntt = np.pad(input, (0, 256-len(input)))
temp_seed_ntt  = np.pad(seed, (0, 256-len(seed)))

ValueError: index can't contain negative values

In [ ]:
mod = 998244353
primitive_root = 3
root = pow(primitive_root, (mod - 1) // 256, mod)

A = NTT(temp_input, root, mod)
B = NTT(seed, root, mod)

C = [(a * b) % mod for a, b in zip(A, B)]

output_NTT_based_conv = inverse_NTT(C, root, mod)
print((output_NTT_based_conv[-output_len:]))

[756462786, 102436228, 519593514, 634154215, 669692052, 580487585, 653650115, 161042377, 724045431, 326711069, 217543265, 974840794, 209784399, 295383711, 163009163, 76563839, 943025389, 319981519, 360398349, 282991130, 653005406, 737366241, 482861691, 276293850, 636387160, 263098553, 580487585, 713103752, 157152765, 274434203, 134475022, 828694511, 932501998, 656896024, 791410208, 991129199, 533224176, 900180302, 415536257, 490519416, 654382533, 508005593, 537166868, 69405874, 227984096, 202641059, 311043993, 580487585, 614120678, 129325616, 716707984, 572884555, 818480487, 977070132, 90332862, 16691461, 73549414, 326327759, 152915538, 937411539, 8088747, 348001552, 89893954, 163509290, 334844210, 476413975, 382231009, 824410225, 580487585, 0]


Odd-even thing that i was thinking is not possible here. LOL!

## dividing a FFT into 2 parts and then computing the output