In [29]:
import numpy as np
import random

In [20]:
def fft(x):
    N = len(x)
    if N == 1:
        return x

    # FFT of even and odd indices
    E = fft(x[0::2])
    O = fft(x[1::2])

    # Twiddle factors
    W = np.exp(-2j * np.pi * np.arange(N) / N)

    # Combine
    X = np.zeros(N, dtype=complex)
    for k in range(N // 2):
        X[k]         = E[k] + W[k] * O[k]
        X[k + N//2]  = E[k] - W[k] * O[k]

    return X

        



In [21]:
signal =  np.random.rand(32)
fft_X = fft(signal)
fft_X

array([15.47869935+0.j        , -0.85754611-0.63860633j,
        0.54562899-1.55358193j, -0.83234701+0.41506661j,
        0.98659508+0.87351963j,  2.37850753-0.26108718j,
       -1.77606716+1.099444j  , -0.67046444-0.89001771j,
       -1.76804696+0.33426956j, -1.3872013 +0.63689317j,
        0.3732402 -0.20674862j,  1.29539304+0.32559123j,
       -3.3491494 -1.88964748j, -0.63990045+0.50856646j,
        0.23067942-1.85318755j, -0.42435915-0.25761246j,
       -3.31071502+0.j        , -0.42435915+0.25761246j,
        0.23067942+1.85318755j, -0.63990045-0.50856646j,
       -3.3491494 +1.88964748j,  1.29539304-0.32559123j,
        0.3732402 +0.20674862j, -1.3872013 -0.63689317j,
       -1.76804696-0.33426956j, -0.67046444+0.89001771j,
       -1.77606716-1.099444j  ,  2.37850753+0.26108718j,
        0.98659508-0.87351963j, -0.83234701-0.41506661j,
        0.54562899+1.55358193j, -0.85754611+0.63860633j])

In [22]:
X = np.fft.fft(signal)

In [23]:
Y = np.fft.ifft(X)
print(abs(Y))
print(signal)

[0.01180965 0.8003282  0.35001078 0.66017401 0.16298961 0.51144641
 0.90578292 0.92928572 0.12044819 0.88994212 0.07090944 0.1124943
 0.52694588 0.31533564 0.99392007 0.67283941 0.15404939 0.79869995
 0.33677454 0.96194407 0.7976462  0.3209198  0.08657383 0.70656432
 0.20204049 0.72222543 0.51452323 0.11080094 0.18204319 0.17132126
 0.66752474 0.7103856 ]
[0.01180965 0.8003282  0.35001078 0.66017401 0.16298961 0.51144641
 0.90578292 0.92928572 0.12044819 0.88994212 0.07090944 0.1124943
 0.52694588 0.31533564 0.99392007 0.67283941 0.15404939 0.79869995
 0.33677454 0.96194407 0.7976462  0.3209198  0.08657383 0.70656432
 0.20204049 0.72222543 0.51452323 0.11080094 0.18204319 0.17132126
 0.66752474 0.7103856 ]


In [24]:
x = np.array([1, 2, 3, 4], dtype=float)

# FFT
X = np.fft.fft(x)

# Inverse FFT
x_rec = np.fft.ifft(X)

In [25]:
print(x)
print(abs(x_rec))

[1. 2. 3. 4.]
[1. 2. 3. 4.]


In [28]:
import numpy as np

# Coefficients of the polynomial
a = np.array([1, 2, 3, 4], dtype=float)

# Zero-pad to avoid circular convolution
n = len(a)
size = 2 * n - 1

A = np.fft.fft(a, size)
C = A * A
c = np.fft.ifft(C)
print(c)
# Remove tiny numerical errors
c = np.round(np.real(c)).astype(int)

print("Result coefficients:")
print(c)


[ 1.+0.j  4.+0.j 10.+0.j 20.+0.j 25.+0.j 24.+0.j 16.+0.j]
Result coefficients:
[ 1  4 10 20 25 24 16]


In [ ]:
n = 100
r = 70
t = n + r - 1
bits = [random.randint(0, 1) for _ in range(n)]
hash = [random.randint(0, 1) for _ in range(t)]